version: "3.3"

services:
#  Service -> Host name pre ostatne services
  database:
    restart: always
    image: sameersbn/postgresql:10-2
    environment:
      - PG_TRUST_LOCALNET=true
      - DB_NAME=event
      - DB_USER=postgres
      - DB_PASS=postgres
      - PG_RUNDIR=/run/postgres
      - PG_LOGDIR=/var/log/postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql

  fronend:
    image: libraryfe
    build: ../eventfe
    ports:
      - "4200:80"
    depends_on:
      - backend1
      - backend2

  backend1:
    image: librarybe
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/event
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    links:
      - redis

  backend2:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/event
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - "8081:8080"
    links:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"


volumes:
  cache:
    driver: local
  data:
  logs:
